spring:
  application:
    name: aigccore
  datasource:
    url: jdbc:mysql://localhost:3306/single_aigccore?useSSL=false&serverTimezone=UTC
    username: root
    password: mofan123
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
    mapper-locations: classpath:mybatis/mappers/*.xml